services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: diecasting-timescaledb
    environment:
      POSTGRES_DB: diecasting_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: securepassword123
      # scram-sha-256 대신 trust 모드 사용 (개발환경)
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - diecasting_network
    restart: unless-stopped
    command: ["postgres", "-c", "shared_preload_libraries=timescaledb"]

  streamlit:
    build: .
    container_name: diecasting-streamlit
    environment:
      - POSTGRES_HOST=timescaledb
      - POSTGRES_PORT=5432
      - POSTGRES_DB=diecasting_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=securepassword123
    ports:
      - "8501:8501"
    depends_on:
      - timescaledb
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./snapshots:/app/snapshots
    networks:
      - diecasting_network
    restart: unless-stopped

volumes:
  timescale_data:

networks:
  diecasting_network:
    driver: bridge